/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.program.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.univcotedazur.l3ia.program.ProgRuntimeModule;
import fr.univcotedazur.l3ia.program.ProgStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ProgIdeSetup extends ProgStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ProgRuntimeModule(), new ProgIdeModule()));
	}
	
}
