/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.program.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ProgScopeProvider extends AbstractProgScopeProvider {

}
