/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.program.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProgAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/univcotedazur/l3ia/program/parser/antlr/internal/InternalProg.tokens");
	}
}
