/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LegoLanguageUiModule extends AbstractLegoLanguageUiModule {

	public LegoLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
