/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.program.ui.tests;

import com.google.inject.Injector;
import fr.univcotedazur.l3ia.program.concrete.textual.bis.ui.internal.BisActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ProgUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BisActivator.getInstance().getInjector("fr.univcotedazur.l3ia.program.Prog");
	}

}
