/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.program;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProgStandaloneSetup extends ProgStandaloneSetupGenerated {

	public static void doSetup() {
		new ProgStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
