/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.program;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProgRuntimeModule extends AbstractProgRuntimeModule {
}
