/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LegoLanguageStandaloneSetup extends LegoLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new LegoLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
