/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LegoLanguageRuntimeModule extends AbstractLegoLanguageRuntimeModule {
}
