/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.ide;


/**
 * Use this class to register ide components.
 */
public class LegoLanguageIdeModule extends AbstractLegoLanguageIdeModule {
}
