/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.univcotedazur.l3ia.LegoLanguageRuntimeModule;
import fr.univcotedazur.l3ia.LegoLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LegoLanguageIdeSetup extends LegoLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LegoLanguageRuntimeModule(), new LegoLanguageIdeModule()));
	}
	
}
