/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.program.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProgScopeProvider extends DelegatingScopeProvider {
}
