/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLegoLanguageScopeProvider extends DelegatingScopeProvider {
}
