/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.ui;

import com.google.inject.Injector;
import fr.univcotedazur.l3ia.projetLegoLanguage.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LegoLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XtextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XtextActivator activator = XtextActivator.getInstance();
		return activator != null ? activator.getInjector(XtextActivator.FR_UNIVCOTEDAZUR_L3IA_LEGOLANGUAGE) : null;
	}

}
